server:
  port: ${API_PORT}

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false
  datasource:
    url: jdbc:mysql://${API_DATABASE_URL}/${API_DATABASE_NAME}?createDatabaseIfNotExist=true&useSSL=${API_DATABASE_USE_SSL}&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: ${API_DATABASE_USERNAME}
    password: ${API_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    ignoreIgnoredMigrations: false
    enabled: true
    baseline-on-migrate: true

